### ISSUE TITLE
styling pass on embedding prezi -- including mobile

### ISSUE THREAD

**Issue by harlantwood** [core-network/website#3]

**Comment by adamapollo** [comment]
Inserted Prezi into a lightbox, made a scalable image clickable, and added link text for backup access. Looks great on Mobile & Desktop.

**Comment by harlantwood** [comment]
Awesome!

On Mon, Jan 11, 2016, 8:58 PM Adam Apollo <notifications@github.com> wrote:

> Closed #3 <https://github.com/core-network/website/issues/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/core-network/website/issues/3#event-511980761>.
>
-- 

Harlan T Wood
EnlightenedStructure.net
It is my commitment to catalyze the creation and adoption of luminous tools
to enable free and open transformation of organizations, individuals, and
the world.  I dream of an age of enlightened creativity, and the end of
scarcity on planet Earth.
